// for some reason I keep having cycling dependency issues with initiating enums. So I just moved them here

export enum Faction {
  arborec = 'Arborec',
  argent_flight = 'Argent flight',
  barony_of_letnev = 'Barony of Letnev',
  clan_of_saar = 'Clan of Saar',
  creuss = 'Creuss',
  crimson_rebellion = 'Crimson Rebellion',
  deepwrought = 'Deepwrought',
  empyrean = 'Empyrean',
  firmament = 'Firmament',
  hacan = 'Hacan',
  jol_nar = 'Jol-Nar',
  keleres = 'Keleres',
  l1z1x = 'L1z1x',
  last_bastion = 'Last Bastion',
  mahact = 'Mahact',
  mentak = 'Mentak',
  muaat = 'Muaat',
  naalu = 'Naalu',
  naaz_rokha = 'Naaz-Rokha',
  nekro = 'Nekro',
  neutral = 'Neutral',
  nomad = 'Nomad',
  obsidian = 'Obsidian',
  ral_nel_consortium = 'Ral Nel Consortium',
  sardakk_norr = "Sardakk N'orr",
  sol = 'Sol',
  titans_of_ul = 'Titans of Ul',
  vuil_raith = "Vuil'Raith",
  winnu = 'Winnu',
  xxcha = 'Xxcha',
  yin = 'Yin',
  yssaril = 'Yssaril',
}

export enum Place {
  space = 'Space',
  ground = 'Ground',
}
