import Head from 'next/head'
import { ChangeEvent, useState } from 'react'
import styled from 'styled-components'
import getBattleReport, { BattleReport } from '../core'
import {
  BattleEffect,
  getAllBattleEffects,
  isBattleEffectRelevant,
} from '../core/battleeffect/battleEffects'
import { getUnitUpgrade } from '../core/battleeffect/unitUpgrades'
import { createParticipant, Participant, Side } from '../core/battleSetup'
import { Race } from '../core/races/race'
import { UnitType } from '../core/unit'

const StyledMain = styled.main`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;

  > * {
    width: 400px;
  }
`

const StyledDiv = styled.div`
  display: flex;
  flex-direction: column;

  > * {
  }
`

const BattleReportDiv = styled.div`
  display: flex;

  > * {
    flex: 1 0 0;
  }
`

export default function Home() {
  const [attacker, setAttacker] = useState<Participant>(createParticipant(Side.attacker))
  const [defender, setDefender] = useState<Participant>(createParticipant(Side.defender))
  const [battleReport, setBattleReport] = useState<BattleReport>()

  const launch = () => {
    const br = getBattleReport(attacker, defender)
    setBattleReport(br)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledMain>
        <h1>ti4 calc</h1>
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <div style={{ display: 'flex' }}>
            <ParticipantView participant={attacker} onChange={setAttacker} />
            <StyledDiv>
              <div>race</div>
              <div>flagship</div>
              <div>warsun</div>
              <div>dreadnought</div>
              <div>carrier</div>
              <div>cruiser</div>
              <div>destroyer</div>
              <div>fighter</div>
              <div>mech</div>
              <div>infantry</div>
              <div>pds</div>
            </StyledDiv>
            <ParticipantView participant={defender} onChange={setDefender} />
          </div>
          <OptionsView
            attacker={attacker}
            attackerOnChange={setAttacker}
            defender={defender}
            defenderOnChange={setDefender}
          />
        </div>
        <button onClick={launch}>roll</button>
        {battleReport && (
          <BattleReportDiv>
            <div>{battleReport.attacker}</div>
            <div>{battleReport.draw}</div>
            <div>{battleReport.defender}</div>
          </BattleReportDiv>
        )}
      </StyledMain>
    </div>
  )
}

interface ParticipantProps {
  participant: Participant
  onChange: (participant: Participant) => void
}

function ParticipantView({ participant, onChange }: ParticipantProps) {
  return (
    <StyledDiv>
      <select
        onChange={(e) => {
          const race = e.target.value as Race
          const newParticipant: Participant = {
            ...participant,
            race,
          }
          onChange(newParticipant)
        }}
        value={participant.race}
      >
        {Object.values(Race).map((race) => {
          return (
            <option key={race} value={race}>
              {race}
            </option>
          )
        })}
      </select>
      <UnitInput participant={participant} unitType={UnitType.flagship} onChange={onChange} />
      <UnitInput participant={participant} unitType={UnitType.warsun} onChange={onChange} />
      <UnitInput participant={participant} unitType={UnitType.dreadnought} onChange={onChange} />
      <UnitInput participant={participant} unitType={UnitType.carrier} onChange={onChange} />
      <UnitInput participant={participant} unitType={UnitType.cruiser} onChange={onChange} />
      <UnitInput participant={participant} unitType={UnitType.destroyer} onChange={onChange} />
      <UnitInput participant={participant} unitType={UnitType.fighter} onChange={onChange} />
      <UnitInput participant={participant} unitType={UnitType.mech} onChange={onChange} />
      <UnitInput participant={participant} unitType={UnitType.infantry} onChange={onChange} />
      <UnitInput participant={participant} unitType={UnitType.pds} onChange={onChange} />
    </StyledDiv>
  )
}

interface UnitInputProps {
  participant: Participant
  unitType: UnitType
  onChange: (participant: Participant) => void
}

function UnitInput({ participant, unitType, onChange }: UnitInputProps) {
  const unitUpgrade = getUnitUpgrade(participant.race, unitType)

  const updateUnitCount = (e: ChangeEvent<HTMLInputElement>) => {
    const newParticipant: Participant = {
      ...participant,
      units: {
        ...participant.units,
        [unitType]: parseInt(e.target.value, 10),
      },
    }
    onChange(newParticipant)
  }

  // TODO if we switch race... do we keep potential race techs?
  const hasUpgrade = participant.unitUpgrades[unitType] ?? false

  return (
    <div style={{ display: 'flex' }}>
      <input
        type="checkbox"
        disabled={!unitUpgrade}
        checked={hasUpgrade}
        onChange={() => {
          const newParticipant: Participant = {
            ...participant,
            unitUpgrades: {
              ...participant.unitUpgrades,
              [unitType]: !hasUpgrade,
            },
          }
          onChange(newParticipant)
        }}
      />
      <input
        type="number"
        min="0"
        max="100"
        value={participant.units[unitType]}
        onChange={updateUnitCount}
      />
    </div>
  )
}

interface OptionsProps {
  attacker: Participant
  attackerOnChange: (participant: Participant) => void
  defender: Participant
  defenderOnChange: (participant: Participant) => void
}

const OptionsDiv = styled.div`
  display: flex;
  > * {
    flex: 1 0 0;
  }
`

function OptionsView({ attacker, attackerOnChange, defender, defenderOnChange }: OptionsProps) {
  const battleEffects = getAllBattleEffects()
  const relevantBattleEffects = battleEffects.filter((effect) => effect.type !== 'unit-upgrade')
  // .filter((effect) => {
  //   return isBattleEffectRelevantForSome(effect, [attacker, defender])
  // })

  return (
    <div>
      <OptionsDiv>
        {getDirectHitCheckbox(attacker, attackerOnChange)}
        <span>Risk direct hit</span>
        {getDirectHitCheckbox(defender, defenderOnChange)}
      </OptionsDiv>
      {relevantBattleEffects.map((effect) => {
        const attackerView = getBattleEffectCheckbox(effect, attacker, attackerOnChange)
        const defenderView = getBattleEffectCheckbox(effect, defender, defenderOnChange)

        return (
          <OptionsDiv key={effect.name}>
            {attackerView}
            <span>{effect.name}</span>
            {defenderView}
          </OptionsDiv>
        )
      })}
    </div>
  )
}

const getDirectHitCheckbox = (
  participant: Participant,
  onChange: (participant: Participant) => void,
) => {
  return (
    <input
      type="checkbox"
      checked={participant.riskDirectHit}
      onChange={() => {
        const newParticipant: Participant = {
          ...participant,
          riskDirectHit: !participant.riskDirectHit,
        }
        onChange(newParticipant)
      }}
    />
  )
}

const getBattleEffectCheckbox = (
  effect: BattleEffect,
  participant: Participant,
  onChange: (participant: Participant) => void,
) => {
  return (
    <input
      type="checkbox"
      name="scales"
      checked={participant.battleEffects.some((e) => e.name === effect.name)}
      onChange={(e) => {
        if (e.target.checked) {
          const newParticipant: Participant = {
            ...participant,
            battleEffects: [...participant.battleEffects, effect],
          }
          onChange(newParticipant)
        } else {
          const newParticipant: Participant = {
            ...participant,
            battleEffects: participant.battleEffects.filter((e) => e.name !== effect.name),
          }
          onChange(newParticipant)
        }
      }}
      disabled={!isBattleEffectRelevant(effect, participant)}
    />
  )
}
